### ISSUE TITLE
Missing any time of internal logging

### ISSUE THREAD

**Issue by execretor** [rfoltyns/log4j2-elasticsearch#10]
Please provide any kind of internal logging. 
At this moment i have a problem with an async appender that switches on a failover appender but there is no log to check the exact error that occurs.

**Comment by rfoltyns** [comment]
Makes sense. I thought about it as well. I'll work a bit more on failover soon.

**Comment by execretor** [comment]
We are using jest module

**Comment by rfoltyns** [comment]
@execretor ok, it will be resolved in 1.3.0

**Comment by rfoltyns** [comment]
@execretor Could you please have a look at the latest release? There's not much error info added by default `JestHttp`, so I couldn't do much. But, `BufferedJestHttp` uses different response model and have more precise error messages.

**Comment by execretor** [comment]
Commits seems to be corrects (logging to warn is ok for me). Now we are testing your library in a performance test environment to test its stability (library is used by a program that receive more that 100000 connections x seconds at peaks and should log to elasticsearch every connection).
So, when the release 1.4 will be ok we will try to test it.

**Comment by rfoltyns** [comment]
@execretor How many hosts are handling the load? Feel free to drop me an email - I can give you some tuning options.

**Comment by execretor** [comment]
The answer is very simple...only 1 :)
If we encounter any problem i will write you an email with  more information.

**Comment by rfoltyns** [comment]
100k/sec may allocate gigabytes of memory atm causing huge GC pressure. Good luck! :)

Consider using [object pooling](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-core#object-pooling) released in 1.3.0 if you can afford to loose logs when ES cluster is down or slow (there's no redirection to `FailoverPolicy` on `pool.getPooled` exceptions so far, will be added in 1.4). With object pooling I'd expect a memory throughput ~250MB-500MB/sec (depending on log size) coming mostly from serialization and Apache HC.

Let me know when you get some results. I've tested it only at 5-20k so far.

**Comment by execretor** [comment]
During out test we have found some errors, such as 

2019-01-25 03:16:54,541 pool-17-thread-9 ERROR An exception occurred processing Appender cksLoggingAppender java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at io.searchbox.core.Bulk.getData(Bulk.java:64)
at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:101)
at io.searchbox.client.http.JestHttpClient.executeAsync(JestHttpClient.java:80)
at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:115)
at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:107)
at org.appenders.log4j2.elasticsearch.BulkEmitter.notifyListener(BulkEmitter.java:73)
at org.appenders.log4j2.elasticsearch.BulkEmitter.add(BulkEmitter.java:84)
at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.add(AsyncBatchDelivery.java:88)
at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.add(AsyncBatchDelivery.java:43)
at org.appenders.log4j2.elasticsearch.ElasticsearchAppender.append(ElasticsearchAppender.java:72)
at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:318)
at com.enel.twobeat.cks.listener.handler.KeepAliveEventHandler.sessionOpened(KeepAliveEventHandler.java:77)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionOpened(DefaultIoFilterChain.java:789)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:476)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:48)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:922)
at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:101)
at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by rfoltyns** [comment]
It's a bug in my code. I need to improve the handover of collected items to BatchListener.
Could you open a separate issue for that? How often does it happen? Could you post your config?

**Comment by execretor** [comment]
Opened new issue  #14

**Comment by rfoltyns** [comment]
Thank you! Is the failure logging better in 1.3.0/1.3.1? If so, could you close this issue please? Otherwise, I'm open for suggestions and/or PRs.

**Comment by rfoltyns** [comment]
> Commits seems to be corrects (logging to warn is ok for me)
Closing as the main issue was addressed and CME addressed in scope of other issue.   
@execretor Feel free to reopen/create new issue if you'd like to see more changes in the logging.
