### ISSUE TITLE
Add template in classpath

### ISSUE THREAD

**Issue by kejsiStruga** [rfoltyns/log4j2-elasticsearch#11]
Hi, I'd like to ask on how I can add the template within the classpath?
I tried to add it in the resource folder and then change the value of the path param but to no avail!

Thank you!

**Comment by foltyr01** [comment]
@kejsiStruga Make sure that the template file actually gets to the resulting jar with your code.

I believe that a fairly good examples can be found in `log4j2-elasticsearch-jest` module in [SmokeTest - programmatic config](https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-jest/src/test/java/org/appenders/log4j2/elasticsearch/jest/smoke/SmokeTest.java) or [log4j2.xml](https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-jest/src/test/resources/log4j2.xml). In both examples template file is in the root of resources folder, meaning that it should be available in the root of your jar.

**Comment by kejsiStruga** [comment]
Hey @foltyr01 thanks for the reply again :)
Indeed, I do have the file in my resources folder. 

I did test the plugin in another though (which doesn't run on docker).

Also, I added the json template within xml tags, to avoid the file altogether.

Now here is what error I get:
```

2019-01-11 19:48:20,440 main ERROR Could not create plugin of type class org.appenders.log4j2.elasticsearch.JacksonMixIn for element JacksonMixIn org.apache.logging.log4j.core.config.ConfigurationException: Cannot load mixInClass: org.apache.logging.log4j.core.jackson.TestLogEventMixIn for JacksonMixIn
	at org.appenders.log4j2.elasticsearch.JacksonMixIn$Builder.loadClass(JacksonMixIn.java:84)

```

**Comment by kejsiStruga** [comment]
@foltyr01 thanks!

Update:

After all, I now get this error:

```
java.lang.ExceptionInInitializerError
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
	at io.searchbox.client.config.HttpClientConfig$Builder.build(HttpClientConfig.java:297)
	at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$JestClientProvider.createClient
```

A quick google search suggested I had to add the **httpclient** mvn dependency, yet, the error prevails. Do you have any suggestions? Is there any place where I can disable ssl?
