### ISSUE TITLE
ConcurrentModificationException error

### ISSUE THREAD

**Issue by execretor** [rfoltyns/log4j2-elasticsearch#14]
During logging operation the appender raises this exception.

2019-01-25 03:16:54,541 pool-17-thread-9 ERROR An exception occurred processing Appender cksLoggingAppender java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at io.searchbox.core.Bulk.getData(Bulk.java:64)
at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:101)
at io.searchbox.client.http.JestHttpClient.executeAsync(JestHttpClient.java:80)
at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:115)
at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:107)
at org.appenders.log4j2.elasticsearch.BulkEmitter.notifyListener(BulkEmitter.java:73)
at org.appenders.log4j2.elasticsearch.BulkEmitter.add(BulkEmitter.java:84)
at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.add(AsyncBatchDelivery.java:88)
at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.add(AsyncBatchDelivery.java:43)
at org.appenders.log4j2.elasticsearch.ElasticsearchAppender.append(ElasticsearchAppender.java:72)
at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:318)
at com.enel.twobeat.cks.listener.handler.KeepAliveEventHandler.sessionOpened(KeepAliveEventHandler.java:77)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionOpened(DefaultIoFilterChain.java:789)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:476)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:48)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:922)
at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:101)
at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Our logger configuration is:
```
                <Elasticsearch name="cksLoggingAppender">
			<JsonLayout compact="true">
                        <KeyValuePair key="uuid" value="$${ctx:uuid}"/>
				<KeyValuePair key="server.address" value="${host}"/>
				<KeyValuePair key="env" value="${env}"/>
				<KeyValuePair key="process" value="KA-LOG"/>
				<KeyValuePair key="event-date" value="$${date:yyyy-MM-d'T'HH:mm:ss.S}" />
			</JsonLayout>
			<RollingIndexName indexName="events-cks" pattern="yyyy-MM-dd" timeZone="Europe/Warsaw" />
			<AsyncBatchDelivery>
				<IndexTemplate name="template" path="${sys:cks.home}/config/elasticsearch/events-cks-template.json" />
				<JestHttp serverUris="URLPLACEHOLDER" />
			</AsyncBatchDelivery>
		</Elasticsearch>

                <Logger name="cksLogging" level="trace" additivity="false">
			<AppenderRef ref="cksLoggingAppender"/>
		</Logger>

**Comment by rfoltyns** [comment]
Couple of things worth mentioning:
- `AsyncBatchDelivery` has default `batchSize` set to 1000 and `deliveryInterval` set to 1000; at 100k/sec, I'd not recommend sending 100 bulks every second as the ES ingestion process may start to suffer; see performance-related articles referenced [here](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-core#delivery-frequency); also `JestHttp` connection pools and timeouts may need some adjustments
- `io.searchbox.Bulk.Builder` uses LinkedList under the hood and there's already an issue created for this in Jest project; however, `org.appenders.log4j2.elasticsearch.jest.BufferedBulk.Builder` uses ConcurrentLinkedQueue instead; you can switch to `JestBufferedHttp` until I have a fix for the ConcurrentModificationException; switch may lead to partial log loss when conditions for mentioned exceptions occur, instead of losing the whole batch 
- eventual switch to `JestBufferedHttp` mentioned before, would require `BufferedSource` as input; currently, it can be created only by `JacksonJsonLayout:PooledItemSourceFactory`, which would make your `KeyValuePair` decoration impossible (I'll probably add support for `additionalProperties` in future releases)

**Comment by rfoltyns** [comment]
This bug was a mix of io.searchbox.core.Bulk being backed by LinkedList and issues in BulkEmitter batch delivery - lack of `AsyncLogger` exposed them instantly.

@execretor Could you retest with the latest release (1.3.2)? Also, could you try the `AsyncLogger`? It will vastly improve the logging throughput and latency.

**Comment by rfoltyns** [comment]
@execretor This issue was fixed in 1.3.2. Did you manage to retest it yet?

**Comment by execretor** [comment]
Sorry but our code Is now in uat testing environment and for now we are not planning a new release before some months.

**Comment by rfoltyns** [comment]
Closing due to lack of activity.
