### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by paskalka** [rfoltyns/log4j2-elasticsearch#19]
Hello,

i got :
java.lang.IllegalAccessError: tried to access method org.apache.http.client.entity.EntityBuilder.<init>()V from class org.apache.http.client.entity.ByteBufEntityBuilder
	at org.apache.http.client.entity.ByteBufEntityBuilder.<init>(ByteBufEntityBuilder.java:10)
	at org.appenders.log4j2.elasticsearch.jest.BufferedJestHttpClient.prepareRequest(BufferedJestHttpClient.java:66)
	at org.appenders.log4j2.elasticsearch.jest.BufferedJestHttpClient.executeAsync(BufferedJestHttpClient.java:47)
	at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:186)
	at org.appenders.log4j2.elasticsearch.jest.JestHttpObjectFactory$1.apply(JestHttpObjectFactory.java:169)
	at org.appenders.log4j2.elasticsearch.BulkEmitter.notifyListener(BulkEmitter.java:93)
	at org.appenders.log4j2.elasticsearch.BulkEmitter$1.run(BulkEmitter.java:129)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Thanks for your help

**Comment by rfoltyns** [comment]
@paskalka please verify the version of `org.apache.httpcomponents:httpclient:jar` on your classpath. Jest ships with 4.5.2.

**Comment by paskalka** [comment]
Hello,
I ships it with 4.5.2 , but i got the same issue
Best regards

**Comment by paskalka** [comment]
Hi,
The issue occurred when i submit a job in  Hortonwork Yarn/Spark . Now Hortonwork also use httpcomponents-client, so you right it's seems to be a classloader issue. 
Thanks you very much for your help
