### ISSUE TITLE
Error in Appenders and loggers

### ISSUE THREAD

**Issue by Parasxidis** [rfoltyns/log4j2-elasticsearch#35]
Hi, I'm getting the next error message when I run my application:
2020-02-05 15:57:11,466 WrapperListener_start_runner ERROR Appenders contains an invalid element or attribute "Elasticsearch"
2020-02-05 15:57:11,487 WrapperListener_start_runner ERROR loggers Loggers has no parameter that matches element AppenderRef

Here is my log4j2.xml:

``<?xml version="1.0" encoding="utf-8"?>
<Configuration status="INFO" name="CLOUDHUB" packages="com.mulesoft.ch.logging.appender,com.splunk.logging">
    <Appenders>

			<Elasticsearch name="elasticsearchAsyncBatch">
        		<IndexName indexName="log4j2" />
        		<AsyncBatchDelivery batchSize="1000" deliveryInterval="5000" >
            		<IndexTemplate name="log4j2" path="classpath:indexTemplate.json" />
            		<JestHttp serverUris="http://localhost:9200" mappingType="_doc"/>
        		</AsyncBatchDelivery>
    		</Elasticsearch>
    </Appenders>
    <Loggers>
        
        
        <AsyncLogger name="org.mule.service.http" level="WARN"/>
        <AsyncLogger name="org.mule.extension.http" level="WARN"/>
    
		        
        <AsyncLogger name="org.mule.runtime.core.internal.processor.LoggerMessageProcessor" level="INFO"/>
        <AsyncLogger name="org.mule" level="INFO"/>
        <AsyncLogger name="com.mulesoft" level="INFO"/>
		
		<AsyncLogger name="com.gigaspaces" level="ERROR"/>
        <AsyncLogger name="com.j_spaces" level="ERROR"/>
        <AsyncLogger name="com.sun.jini" level="ERROR"/>
        <AsyncLogger name="net.jini" level="ERROR"/>
        <AsyncLogger name="org.apache" level="WARN"/>
        <AsyncLogger name="org.apache.cxf" level="WARN"/>
        <AsyncLogger name="org.springframework.beans.factory" level="WARN"/>
        <AsyncLogger name="org.mule" level="INFO"/>
        <AsyncLogger name="com.mulesoft" level="INFO"/>
        <AsyncLogger name="org.jetel" level="WARN"/>
        <AsyncLogger name="Tracking" level="WARN"/>
 
  		<AsyncLogger name="elasticsearch" level="info" additivity="false"/>
  			<AppenderRef ref="elasticsearchAsyncBatch" />

        <AsyncRoot level="INFO">

        </AsyncRoot>
    </Loggers>
</Configuration>``

**Comment by rfoltyns** [comment]
@Parasxidis I'm afraid that you'll have to provide much more info here. There must be some more error logs or stacktraces around it.

Otherwise, I can't give you an explanation why `"Appenders contains an invalid element or attribute "Elasticsearch"`. Dependencies missing? Config/init errors? SPI issues? I just can't tell based on the nfo you provided.

**Comment by rfoltyns** [comment]
Closing due to lack of sufficient information to proceed.

Please visit [examples](https://github.com/rfoltyns/log4j2-elasticsearch-examples) and verify your configuration.

**Comment by BugraAkdagPXL** [comment]
I have this same exact issue right now, no other error logs or stack traces available. Dependencies should be alright.

**Comment by rfoltyns** [comment]
@BugraAkdagPXL Can you see more once you enable status logging?

```xml
<Configuration status="DEBUG">
... your config ..
</Configuration>
```

Can you post your Log4j2 config?

Did you try [examples](https://github.com/rfoltyns/log4j2-elasticsearch-examples) already? Try to verify your config there.

**Comment by BugraAkdagPXL** [comment]
2022-03-18 08:47:49,233 WrapperListener_start_runner DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2022-03-18 08:47:49,234 WrapperListener_start_runner ERROR Appenders contains an invalid element or attribute "Elasticsearch"
2022-03-18 08:47:49,234 WrapperListener_start_runner DEBUG createAppenders(={file})
2022-03-18 08:47:49,234 WrapperListener_start_runner DEBUG Building Plugin[name=asyncLogger, class=org.apache.logging.log4j.core.async.AsyncLoggerConfig].
2022-03-18 08:47:49,234 WrapperListener_start_runner DEBUG createLogger(additivity="true", level="WARN", name="org.mule.service.http", includeLocation="null", ={}, ={}, Configuration(cloudhub), Filter=null)
2022-03-18 08:47:49,235 WrapperListener_start_runner DEBUG Building Plugin[name=asyncLogger, class=org.apache.logging.log4j.core.async.AsyncLoggerConfig].
2022-03-18 08:47:49,235 WrapperListener_start_runner DEBUG createLogger(additivity="true", level="WARN", name="org.mule.extension.http", includeLocation="null", ={}, ={}, Configuration(cloudhub), Filter=null)
2022-03-18 08:47:49,235 WrapperListener_start_runner DEBUG Building Plugin[name=asyncLogger, class=org.apache.logging.log4j.core.async.AsyncLoggerConfig].
2022-03-18 08:47:49,236 WrapperListener_start_runner DEBUG createLogger(additivity="true", level="INFO", name="org.mule.runtime.core.internal.processor.LoggerMessageProcessor", includeLocation="null", ={}, ={}, Configuration(cloudhub), Filter=null)
2022-03-18 08:47:49,236 WrapperListener_start_runner DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2022-03-18 08:47:49,236 WrapperListener_start_runner DEBUG createAppenderRef(ref="ELK", level="null", Filter=null)

Little bit more but still no detailed stacktrace. 

Here is my log4j

<?xml version="1.0" encoding="utf-8"?>
<Configuration name="cloudhub" packages="com.mulesoft.ch.logging.appender" status="DEBUG">
    <Properties>
	    <Property name="env">local</Property>
	    <Property name="logs.destination">ELK</Property>
	    <Property name="apiName">salesforce-sapi</Property>
        <Property name="elk.password">HIDDEN</Property>
	  </Properties>

    

    <Appenders>
        <RollingFile name="file" fileName="${sys:mule.home}${sys:file.separator}logs${sys:file.separator}${sys:apiName}-implementation.log" 
                 filePattern="${sys:mule.home}${sys:file.separator}logs${sys:file.separator}${sys:apiName}-implementation-%i.log">
            <PatternLayout pattern="%-5p %d [%t] [processor: %X{processorPath}; event: %X{correlationId}] %c: %m%n" />
            <SizeBasedTriggeringPolicy size="10 MB" />
            <DefaultRolloverStrategy max="10"/>
        </RollingFile>

		<Elasticsearch name="ELK">
			<IndexName indexName="log4j2-elasticsearch-hc"/>
			<JacksonJsonLayout>
				<NonEmptyFilter/>
				<VirtualProperty name="correlationId" value="$${ctx:correlationId:-}"/>
				<VirtualProperty name="apiName" value="${sys:apiName}"/>
				<VirtualProperty name="env" value="${sys:env}"/>
				<JacksonModuleExample/>
            	<PooledItemSourceFactory poolName="itemPool" itemSizeInBytes="1024" initialPoolSize="3000"/>
        	</JacksonJsonLayout>
        	<AsyncBatchDelivery batchSize="1000" deliveryInterval="10000" >
        		<HCHttp serverUris="URL">
        			<Security>
        				<BasicCredentials username="USERNAME" password="PASSWORD"/>
        			</Security>
        		</HCHttp>
        	</AsyncBatchDelivery>
		</Elasticsearch>
    </Appenders>
    <Loggers>
        
        
        
        <AsyncLogger name="org.mule.service.http" level="WARN"/>
        <AsyncLogger name="org.mule.extension.http" level="WARN"/>
    
		        
        <AsyncLogger name="org.mule.runtime.core.internal.processor.LoggerMessageProcessor" level="INFO"/>
 
        <AsyncRoot level="INFO">
            <AppenderRef ref="${sys:logs.destination}" />
        </AsyncRoot>
    </Loggers>
</Configuration>

**Comment by rfoltyns** [comment]
Please remove `<JacksonModuleExample/>` (unless your own implementation), it's not a part of released binary and may cause this failure.

**Comment by BugraAkdagPXL** [comment]
Thank you for the fast response but sadly enough this did not resolve the problem. Is the following part necessary in the Pom? Since this is the only thing I do not have in my own pom.


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
                
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by rfoltyns** [comment]
In `log4j2-elasticsearch-examples` project, this part of POM forces Spring Boot to use Log4j2. Harmless (and necessary).

You're using `PooledItemSourceFactory` for item buffers in layout. With this configuration, you need to provide a pool for batch buffers in HCHttp config. Try this:

```xml
<HCHttp serverUris="URL">
    <PooledItemSourceFactory poolName="batchPool" itemSizeInBytes="1024000" initialPoolSize="3"/>
    <Security>
        <BasicCredentials username="USERNAME" password="PASSWORD"/>
    </Security>
</HCHttp>
```

Batch buffer `itemSizeInBytes` should be `itemPool.itemSizeInBytes * asyncBatchDelivery.batchSize`. It can be lower, but  - depending on your message size - application may need to extend/shrink these buffers back and forth too often causing too much garbage and effectively defeating the purpose of these pools.

**Comment by BugraAkdagPXL** [comment]
Log4j is already being used in our project. We already used log4j to send messages to Elasticsearch over HTTP. We had memory issues and wanted to try this out. But when reading in the logs its clear that the <Elasticsearch> tag is not recognised in the log4j xml. So any changes made within the Elasticsearch tag is not changing anything.

In my dependencies I have the following
		<dependency>
            <groupId>org.appenders.log4j</groupId>
            <artifactId>log4j2-elasticsearch-hc</artifactId>
            <version>${appenders.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.appenders.st</groupId>
            <artifactId>appenders-jackson-st</artifactId>
            <version>1.0.1</version>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-afterburner</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>4.1.32.Final</version>
        </dependency>
        
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>3.19.40</version>
        </dependency>
        
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.2</version>
        </dependency>

**Comment by rfoltyns** [comment]
Which version are you using? (`${appenders.version}`)

Could you post your current Log4j2 config?

Configuration below starts just fine in with [log4j2-elasticsearch-hc-springboot example](https://github.com/rfoltyns/log4j2-elasticsearch-examples/tree/master/log4j2-elasticsearch-hc-springboot) and unchanged pom(!). Log delivery obviously fails because MalformedUrlException, but Log4j2 initializes successfully.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <Console name="CONSOLE" />

        <Elasticsearch name="elasticsearch">
            <IndexName indexName="log4j2-elasticsearch-hc"/>
            <JacksonJsonLayout>
                <NonEmptyFilter/>
                <VirtualProperty name="correlationId" value="$${ctx:correlationId:-}"/>
                <VirtualProperty name="apiName" value="${sys:apiName}"/>
                <VirtualProperty name="env" value="${sys:env}"/>
                <PooledItemSourceFactory poolName="itemPool" itemSizeInBytes="1024" initialPoolSize="3000"/>
            </JacksonJsonLayout>
            <AsyncBatchDelivery batchSize="1000" deliveryInterval="10000" >
                <HCHttp serverUris="URL">
                    <PooledItemSourceFactory poolName="batchPool" itemSizeInBytes="1024000" initialPoolSize="3"/>
                    <Security>
                        <BasicCredentials username="USERNAME" password="PASSWORD"/>
                    </Security>
                </HCHttp>
            </AsyncBatchDelivery>
        </Elasticsearch>
    </Appenders>

    <Loggers>
        <AsyncLogger name="elasticsearch">
            <AppenderRef ref="elasticsearch" />
        </AsyncLogger>
        <Root level="info">
            <AppenderRef ref="CONSOLE" />
        </Root>
    </Loggers>
</Configuration>
```

Also, on other note, `$${ctx:correlationId:-}` will always be empty if you use `AsyncLogger`, but let's get to that later.

**Comment by BugraAkdagPXL** [comment]
I am using appenders version 1.5.2 and jackson version 2.12.0.

Full log4j:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration name="cloudhub" packages="com.mulesoft.ch.logging.appender" status="DEBUG">
    <Properties>
	    <Property name="env">local</Property>
	    <Property name="logs.destination">ELK</Property>
	    <Property name="apiName">salesforce-sapi</Property>
        <Property name="elk.password">PASSWORD=</Property>
	  </Properties>

    <!--These are some of the loggers you can enable. 
        There are several more you can find in the documentation. 
        Besides this log4j configuration, you can also use Java VM environment variables
        to enable other logs like network (-Djavax.net.debug=ssl or all) and 
        Garbage Collector (-XX:+PrintGC). These will be append to the console, so you will 
        see them in the mule_ee.log file. -->

    <Appenders>
        <RollingFile name="file" fileName="${sys:mule.home}${sys:file.separator}logs${sys:file.separator}${sys:apiName}-implementation.log" 
                 filePattern="${sys:mule.home}${sys:file.separator}logs${sys:file.separator}${sys:apiName}-implementation-%i.log">
            <PatternLayout pattern="%-5p %d [%t] [processor: %X{processorPath}; event: %X{correlationId}] %c: %m%n" />
            <SizeBasedTriggeringPolicy size="10 MB" />
            <DefaultRolloverStrategy max="10"/>
        </RollingFile>
		<Elasticsearch name="ELK">
			<IndexName indexName="log4j2-elasticsearch-hc"/>
			<JacksonJsonLayout>
				<NonEmptyFilter/>
				<VirtualProperty name="correlationId" value="$${ctx:correlationId:-}"/>
				<VirtualProperty name="apiName" value="${sys:apiName}"/>
				<VirtualProperty name="env" value="${sys:env}"/>
            	<PooledItemSourceFactory poolName="itemPool" itemSizeInBytes="1024" initialPoolSize="3000"/>
        	</JacksonJsonLayout>
        	<AsyncBatchDelivery batchSize="1000" deliveryInterval="10000" >
        		<HCHttp serverUris="URL">
        		<PooledItemSourceFactory poolName="batchPool" itemSizeInBytes="1024000" initialPoolSize="3"/>
        			<Security>
        				<BasicCredentials username="USERNAME" password="URL"/>
        			</Security>
        		</HCHttp>
        	</AsyncBatchDelivery>
		</Elasticsearch>
    </Appenders>
    <Loggers>
        
        <!-- Http Logger shows wire traffic on DEBUG. -->
        <!--AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG" /-->
        <AsyncLogger name="org.mule.service.http" level="WARN"/>
        <AsyncLogger name="org.mule.extension.http" level="WARN"/>
    
		<!-- Mule logger -->        
        <AsyncLogger name="org.mule.runtime.core.internal.processor.LoggerMessageProcessor" level="INFO"/>
 
        <AsyncRoot level="INFO">
            <AppenderRef ref="${sys:logs.destination}" />
        </AsyncRoot>
    </Loggers>
</Configuration>
```

**Comment by rfoltyns** [comment]
With the configuration above, if you keep the POM file intact, you should get a log similar to this:

```
[localhost log4j2-elasticsearch-hc-springboot]$ java -jar target/log4j2-elasticsearch-hc-springboot-0.0.1-SNAPSHOT.jar
2022-03-18 11:16:26,242 main INFO No configured resizePolicy found for pool itemPool. Defaulting to UnlimitedResizePolicy
2022-03-18 11:16:26,382 main INFO No configured resizePolicy found for pool batchPool. Defaulting to UnlimitedResizePolicy
2022-03-18 11:16:26,436 main INFO BatchEmitterFactory class found org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory
2022-03-18 11:16:26,437 main INFO BatchEmitterFactory class found org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory
2022-03-18 11:16:26,450 main INFO Using org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory as BatchEmitterServiceProvider
2022-03-18 11:16:26,486 main INFO Pool [batchPool] 3 pooled elements added. Total pooled elements: 3. Took: 9ms
2022-03-18 11:16:26,488 main INFO Pool [ItemSourcePool] 1 pooled elements added. Total pooled elements: 1. Took: 0ms
2022-03-18 11:16:26,508 main INFO Pool [itemPool] 3000 pooled elements added. Total pooled elements: 3000. Took: 19ms
2022-03-18 11:16:26,777 main INFO No configured resizePolicy found for pool itemPool. Defaulting to UnlimitedResizePolicy
2022-03-18 11:16:26,778 main INFO No configured resizePolicy found for pool batchPool. Defaulting to UnlimitedResizePolicy
2022-03-18 11:16:26,782 main INFO BatchEmitterFactory class found org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory
2022-03-18 11:16:26,782 main INFO BatchEmitterFactory class found org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory
2022-03-18 11:16:26,783 main INFO Using org.appenders.log4j2.elasticsearch.hc.BulkEmitterFactory as BatchEmitterServiceProvider
2022-03-18 11:16:26,787 main INFO Pool [batchPool] 3 pooled elements added. Total pooled elements: 3. Took: 1ms
2022-03-18 11:16:26,787 main INFO Pool [ItemSourcePool] 1 pooled elements added. Total pooled elements: 1. Took: 0ms
2022-03-18 11:16:26,791 main INFO Pool [itemPool] 3000 pooled elements added. Total pooled elements: 3000. Took: 2ms
2022-03-18 11:16:26,792 main INFO BulkEmitter: Executor was shutdown gracefully

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.5.RELEASE)

Starting Application v0.0.1-SNAPSHOT on localhost with PID 9085 ((...)log4j2-elasticsearch-hc-springboot-0.0.1-SNAPSHOT.jar started by (...) in (...)log4j2-elasticsearch-examples/log4j2-elasticsearch-hc-springboot)
No active profile set, falling back to default profiles: default
Started Application in 0.831 seconds (JVM running for 1.814)
Hello, World!
2022-03-18 11:16:32,603 main ERROR before-batch failed: Can't resolve address: URL java.lang.IllegalArgumentException: Can't resolve address: URL
        at org.appenders.log4j2.elasticsearch.hc.discovery.ServerInfo.<init>(ServerInfo.java:38)
        at org.appenders.log4j2.elasticsearch.hc.ServerPool.<init>(ServerPool.java:54)
        at org.appenders.log4j2.elasticsearch.hc.HttpClientFactory.createInstance(HttpClientFactory.java:96)
        at org.appenders.log4j2.elasticsearch.hc.HttpClientProvider.createClient(HttpClientProvider.java:45)
        at org.appenders.log4j2.elasticsearch.hc.HttpClientProvider.start(HttpClientProvider.java:63)
        at org.appenders.log4j2.elasticsearch.hc.BatchingClientObjectFactory.lambda$start$2(BatchingClientObjectFactory.java:295)
        at org.appenders.log4j2.elasticsearch.hc.BatchingClientObjectFactory$1.apply(BatchingClientObjectFactory.java:109)
        at org.appenders.log4j2.elasticsearch.hc.BatchingClientObjectFactory$1.apply(BatchingClientObjectFactory.java:97)
        at org.appenders.log4j2.elasticsearch.BulkEmitter.notifyListener(BulkEmitter.java:109)
        at org.appenders.log4j2.elasticsearch.BulkEmitter.doStop(BulkEmitter.java:212)
        at org.appenders.log4j2.elasticsearch.DelayedShutdown.run(DelayedShutdown.java:136)
        at org.appenders.log4j2.elasticsearch.DelayedShutdown.start(DelayedShutdown.java:168)
        at org.appenders.log4j2.elasticsearch.BulkEmitter.stop(BulkEmitter.java:204)
        at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.stop(AsyncBatchDelivery.java:254)
        at org.appenders.log4j2.elasticsearch.ItemSourceAppender.stop(ItemSourceAppender.java:70)
        at org.appenders.log4j2.elasticsearch.ElasticsearchAppender.lifecycleStop(ElasticsearchAppender.java:236)
        at org.appenders.log4j2.elasticsearch.ElasticsearchAppender.stop(ElasticsearchAppender.java:215)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:398)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:375)
        at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
        at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem$ShutdownHandler.run(Log4J2LoggingSystem.java:278)
        at com.github.rfoltyns.Application.main(Application.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.net.MalformedURLException: no protocol: URL
        at java.base/java.net.URL.<init>(URL.java:672)
        at java.base/java.net.URL.<init>(URL.java:568)
        at java.base/java.net.URL.<init>(URL.java:515)
        at org.appenders.log4j2.elasticsearch.hc.discovery.ServerInfo.<init>(ServerInfo.java:36)
        ... 29 more

2022-03-18 11:16:32,605 main WARN Shutdown interrupted: Can't resolve address: URL
```

Once the URL and credentials (and SSL config if needed) are set, it should be good to go.

Could you run the HC SpringBoot example and post your log, please?

**Comment by rfoltyns** [comment]
I just noticed that `IndexTemplate` is also missing. You will not be able to discover your logs in Kibana without it. Date column is `timeMillis` by default.

```xml
<IndexTemplate name="log4j2-elasticsearch-hc-springboot-es-7-test-template" path="classpath:indexTemplate-7.json" />
```

Template file is not a part of the binary, so you'll have to provide it and maintain it on your own (because only you know how would you like to index your logs).

You can either use the trivial template from examples project, this project's test resources or add it manually if the BasicCredentials.user doesn't have enough privileges.

**Comment by BugraAkdagPXL** [comment]
I was missing my packages attribute in my log4j. Sorry for the late answer, was sick last week.

**Comment by rfoltyns** [comment]
@BugraAkdagPXL No worries.

Do you think there's anything that can be done within the scope of this project to avoid these kind of issues. Can be tough if it was simply a misconfigured Mule module.
